sudo: required
language: generic
service:
  - docker
before_install:
  - echo "start createing an image with "start createing an image with dockerfile"
  - docker build -t nicekkong/docker-react -f Dockerfile.dev ./
script:
  - docker run -e CI=true nicekkong/docker-react npm run test -- --coverage
after_success:
  - echo "Test Success"